general:
  linkAddress: about:blank
  implicitlyWaitTime: 2
  webDriverWait: 5
  pageLoadTime: 60
  searchLinkAddress: https://www.google.com/
  headless: false
  recordScreen: false
  close_drivers_before_start: false